name = "discord-bot-worker"
main = "discord-bot-worker-simple.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars.DISCORD_TOKEN = "MTQyNTE1NjcxNDM4NjE2NTk4MA.Gz4gGN.fXpELHcz6-PW4w8aNqwGUaqdo_xswECvBTiSvE"
vars.DISCORD_CLIENT_ID = "1425156714386165980"
vars.API_BASE_URL = "https://5363a3be.gospelways.pages.dev/api/bible-games"
