name = "faith-defenders"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
routes = [
  { pattern = "faithdefenders.pages.dev", zone_name = "faithdefenders.pages.dev" }
]

# R2 Bucket for file storage
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "faith-defenders-files"
preview_bucket_name = "faith-defenders-files-preview"

# CORS configuration for R2 bucket
[[r2_buckets.cors]]
allowed_origins = ["http://localhost:3000", "http://localhost:5173", "http://localhost:5174", "https://*.pages.dev", "https://*.e2b.dev", "https://gospelways.com"]
allowed_methods = ["GET", "HEAD", "OPTIONS"]
allowed_headers = ["*"]
exposed_headers = ["Content-Type", "Content-Length", "ETag"]
max_age_seconds = 3600

# D1 Database (if needed for additional data)
# [[d1_databases]]
# binding = "DB"
# database_name = "faith-defenders-db"
# database_id = ""

# Environment variables
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your_production_jwt_secret_here"
ADMIN_EMAIL = "siagmoo26@gmail.com"
ADMIN_NAME = "Admin"
ADMIN_PASSWORD = "Famous2016?"

# Google OAuth (configure in Cloudflare dashboard - NOT FOR DISCORD BOT)
# GOOGLE_CLIENT_ID = ""
# GOOGLE_CLIENT_SECRET = ""

# Database URL (configure in Cloudflare dashboard)
# DATABASE_URL = ""

# Email service (configure in Cloudflare dashboard)
# RESEND_API_KEY = ""
# FROM_EMAIL = ""

# AI API Configuration (configure in Cloudflare dashboard)
# OPENROUTER_API_KEY = ""
# OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
# AI_MODEL = "x-ai/grok-4-fast:free"

# Durable Objects for real-time messaging and progress tracking
[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "PROGRESS_TRACKER"
class_name = "QuestionGenerationTracker"

[[durable_objects.bindings]]
name = "AI_GENERATOR"
class_name = "AIGenerationDO"

# Discord Bot Worker
[[workers]]
name = "discord-bot-worker"
main = "discord-bot-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
